import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import withLayout from '@/layout/appLayout'

import { Text } from '@mantine/core'
import User from '@/store/user.store'

const inter = Inter({ subsets: ['latin'] })

function Home() {
  const { user } = User()
  console.log(user?.email)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>

        <Text>kefjfmwefweonl</Text>
      </main>
    </>
  )
}

export default withLayout(Home, "Home")